services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=Simple_API_user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 